builds:

  - id: cgo-linux-amd64
    binary: cgo
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
      - CGO_CFLAGS=--sysroot=/sysroot/lib64
      - CGO_LDFLAGS=--sysroot=/sysroot/lib64
      - PKG_CONFIG_SYSROOT_DIR=/sysroot/lib64
      - PKG_CONFIG_PATH=/sysroot/lib64/pkgconfig:/sysroot/share/pkgconfig

archives:
  - format: tar.gz
    id: homebrew
    name_template: "{{ .ProjectName }}.{{ .Os }}.{{ .Arch }}"
    files:
      - none*

# it is necessary to specify the name_template of the snapshot, or else the snapshot gets created with
# two dash(-) which results in a 500 error while downloading
snapshot:
  name_template: "{{ incpatch .Version }}-next"

checksum:
  name_template: "checksums.txt"

changelog:
  skip: true

release:
  prerelease: auto

